### ISSUE TITLE
"Extension host terminated unexpectedly"

### ISSUE THREAD

**Issue by Nostrus** [nrwl/angular-console#818] opened 2019-08-28 11:19 UTC
Today I encountered an error where after starting VS Code I get "Extension host terminated unexpectedly", and all extensions crash. I managed to single out the angular-console extension, and after disabling it everything works fine again. I think it's worth checking out.

**Comment by IT-CASADO** [comment] 2019-08-28 13:24
I have the same problem

**Comment by mrmeku** [comment] 2019-08-28 23:32
@Nostrus @IT-CASADO Can you both tell me what OS you are running on? This is alarming and I want to get a fix in quickly. But I can't reproduce the error locally so far.

If either of you have encourtered this when opening an open source repo in vscode, a link to the repo might be helpful since I could clone it locally and see if I can reproduce that way

**Comment by Nostrus** [comment] 2019-08-29 06:16
I'm on MacOS Mojave 10.14.6. 
I encountered this while developing my own repo, which is an Ionic app. I haven't touched it in the last 2 weeks maybe, but all worked fine before. 
I'm attaching a screenshot of the error log from VS Code, maybe it will help you in identifying the problem:
<img width="941" alt="Screenshot 2019-08-29 at 8 06 43" src="https://user-images.githubusercontent.com/1503990/63914815-8e898c80-ca34-11e9-9283-85abec09b85e.png">

**Comment by IT-CASADO** [comment] 2019-08-29 07:32
I'm on Windows 10.

But I think I found the reason!!
Everything works if I deleted my angular.json configuration file.

Then I tried to narrow down the issue. But only saving this file fixed it for me.

A file compare shows me, that VS Code removed on save some trailing commas.

This is not working:

`
"styles": [
							"./node_modules/@fortawesome/fontawesome-pro/css/all.css",
							"./src/theme-light.scss",
						],
`

See last comma after theme-light.scss.

**Comment by jimb77** [comment] 2019-09-01 20:01
Similar issue here, similar situation to IT-CASADO - in my case angular.json had ended up with a rogue comma after "scripts".

Before (causes the crash) -

` "src/css/styles.scss" ], "scripts": [], }, "configurations": { `

Remove comma (no longer crashes the extension host) - 
` "src/css/styles.scss" ], "scripts": [] }, "configurations": { `

**Comment by mrmeku** [comment] 2019-09-11 19:31
Ah I understand the issue now. I need to add some logic to handle invalid JSONs more gracefully (trailing commas make a JSON invalid). But we should be able to handle these things a bit better than just having the extension crash

**Comment by mrmeku** [comment] 2019-09-12 01:09
This should be fixed with release 8.1.2. If there's a corner case I missed that you run into please do not hesitate to reopen the issue.

Thanks everyone for the bug report!

**Closed by mrmeku** 2019-09-12 01:09 UTC
