### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by LloydNicholson** [nrwl/angular-console#639] opened 2019-04-11 17:54 UTC
- Issue Type: `Performance`
- Extension Name: `angular-console`
- Extension Version: `7.4.7`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/lloydnicholson/nrwl.angular-console-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jaysoo** [comment] 2019-04-16 19:16
@LloydNicholson Thanks for reporting this. We will investigate.

**Comment by mrmeku** [comment] 2019-05-06 19:21
Duplicate of https://github.com/nrwl/angular-console/issues/680
I'm going to use the other issue to track

**Closed by mrmeku** 2019-05-06 19:21 UTC
Labels: perf
