### ISSUE TITLE
Create workspace hangs in v8.0.0 due to google analytics prompt

### ISSUE THREAD

**Issue by dopsonbr** [nrwl/angular-console#719] opened 2019-06-02 20:03 UTC
Creating a new nx workspace hangs in v8.0.0 due to google analytics prompt.
**Angular console info:** version=v8.0.0, type=standalone, os=mac

**Expected behavior:** A new workspace is successfully created without prompts. Running the create workspace command with npx is successful. npx output:
```
~/tmp via ⬢ v10.15.3
➜ rm -rf angular-8-test && npx --ignore-existing create-nx-workspace angular-8-test --directory=angular-8-test --collection=@nrwl/workspace --npmScope=usom --no-skipInstall --no-skipGit --no-interactive
npx: installed 53 in 9.331s
Creating a sandbox with Nx...
ng new "angular-8-test" "--directory=angular-8-test" "--collection=@nrwl/workspace" "--npmScope=usom" "--no-skipInstall" "--no-skipGit" "--no-interactive" --collection=@nrwl/workspace
CREATE angular-8-test/README.md (2696 bytes)
CREATE angular-8-test/angular.json (298 bytes)
CREATE angular-8-test/nx.json (195 bytes)
CREATE angular-8-test/tsconfig.json (509 bytes)
CREATE angular-8-test/tslint.json (1574 bytes)
CREATE angular-8-test/.editorconfig (245 bytes)
CREATE angular-8-test/.gitignore (503 bytes)
CREATE angular-8-test/.prettierignore (57 bytes)
CREATE angular-8-test/.prettierrc (26 bytes)
CREATE angular-8-test/package.json (1145 bytes)
CREATE angular-8-test/.vscode/extensions.json (164 bytes)
CREATE angular-8-test/apps/.gitkeep (1 bytes)
CREATE angular-8-test/libs/.gitkeep (0 bytes)
CREATE angular-8-test/tools/tsconfig.tools.json (218 bytes)
CREATE angular-8-test/tools/schematics/.gitkeep (0 bytes)
    Successfully initialized git.
```

**Actual behavior:**
```
new-workspace angular-8-test --directory=angular-8-test --collection=@nrwl/workspace --npmScope=usom --no-skipInstall --no-skipGit --no-interactive

npm init -y
Wrote to /private/var/folders/cg/dk_vx3351vg_2srbw7ktbnzh0000gn/T/tmp-37450RTS65YJkufTm/package.json:

{
  "name": "tmp-37450RTS65YJkufTm",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


npm install @angular/cli@latest

> @angular/cli@8.0.1 postinstall /private/var/folders/cg/dk_vx3351vg_2srbw7ktbnzh0000gn/T/tmp-37450RTS65YJkufTm/node_modules/@angular/cli
> node ./bin/postinstall/script.js

? Would you like to share anonymous usage data with the Angular Team at Google u
nder
Google’s Privacy Policy at https://policies.google.com/privacy? For more details
 and
how to change this setting, see http://angular.io/analytics. (y/N) 
```

**Comment by fdlsistemi** [comment] 2019-06-04 13:24
Same issue here.

**Comment by Florian3003** [comment] 2019-06-06 06:31
Same issue here.

**Comment by clickboxmobile** [comment] 2019-06-08 18:46
Same here.

**Comment by alexnoise79** [comment] 2019-06-11 07:33
Console should be editable, is not even possible to copy from it.

**Comment by ryanbrear** [comment] 2019-06-12 09:51
Same problem here.

**Comment by mapsgeek** [comment] 2019-06-13 01:18
solution would be updating the angular cli from outside angular console, running `npm install @angular/cli@latest`, then open the console and create the workspace it will work fine

**Comment by fdlsistemi** [comment] 2019-06-13 01:23
Not sure about that, mapsgeek.
I had the above-mentioned issue last week on a fresh, brand new install... 

Can’t test it right now (currently on vacation): can anyone give it a try?

**Comment by mapsgeek** [comment] 2019-06-13 01:26
well i had the same problem few minutes ago and that's what i did and solved it !

**Comment by fdlsistemi** [comment] 2019-06-13 01:27
Great, thanks for the confirmation then!  =))

**Comment by joelmuskwe** [comment] 2019-06-13 07:09
@mapsgeek Thanks it works but this solves the problem but i think the issue is that they assume that angular-console users are using npm for managing packages. For me i was purely using yarn hence the issue was arising till i globally installed @angular/cli in npm. so now i have to manage angular cli versions in both yarn and npm

**Comment by mapsgeek** [comment] 2019-06-13 07:26
@joelmuskwe well i think yes they should fix it somehow but at least people can do this for temporary workaround.

**Comment by yglin** [comment] 2019-06-19 08:27
Stuck there, too.
From @mapsgeek's solution, Installing latest Angular CLI once, globally also, solves the problem, thanks~

`npm install -g @angular/cli@latest
`

**Comment by mrmeku** [comment] 2019-07-19 19:23
Will be fixed in our next release next week

**Closed by mrmeku** 2019-07-19 19:23 UTC

**Comment by papirovdavid** [comment] 2019-08-09 09:32
Waiting for fix

**Comment by joelmuskwe** [comment] 2019-08-14 06:47
We are still waiting it's now close to a month, is the release still coming out. We have been enjoying this tool especially for introducing it to new developers but it's now getting worrying and actually contemplating now on removing it from our dev pipeline.

**Comment by st-clair-clarke** [comment] 2019-08-23 23:07
When will the fix be released?

**Comment by emilkoto** [comment] 2019-08-29 08:47
I have been solved it! 
Just put in some terminal (and restart angular console):
`ng analytics off`
Extracted from: https://angular.io/analytics
