### ISSUE TITLE
angular-console Extension causes high cpu load

### ISSUE THREAD

**Issue by chandramuralis** [nrwl/angular-console#682] opened 2019-05-08 20:58 UTC
- Issue Type: `Performance`
- Extension Name: `angular-console`
- Extension Version: `7.4.19`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.33.1`

[nrwl.angular-console-unresponsive.cpuprofile.txt](https://github.com/nrwl/angular-console/files/3159262/nrwl.angular-console-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by mrmeku** [comment] 2019-05-14 10:26
Duplicate of https://github.com/nrwl/angular-console/issues/680

**Closed by mrmeku** 2019-05-14 10:26 UTC
